# Generated by Django 2.2.5 on 2019-09-30 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Todos', max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Celular', max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('contact_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Personal', max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('contact_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Casa', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('contact_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact')),
            ],
        ),
    ]
