# Generated by Django 2.2.5 on 2019-09-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
