# Generated by Django 2.2.5 on 2019-10-03 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191002_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('homeplace', 'Casa'), ('workplace', 'Trabajo'), ('otherplace', 'Otro')], default='Casa', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.CharField(choices=[('main', 'Personal'), ('workmail', 'Trabajo'), ('other', 'Otro')], default='Personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Contact'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(choices=[('cellphone', 'Celular'), ('workphone', 'Trabajo'), ('homephone', 'Casa'), ('landline', 'Fijo'), ('otherphone', 'Otro')], default='Celular', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
