# Generated by Django 2.2.5 on 2019-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191003_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Trabajo', 'Trabajo'), ('Otro', 'Otro')], default='Casa', max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Trabajo', 'Trabajo'), ('Otro', 'Otro')], default='Personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Trabajo', 'Trabajo'), ('Casa', 'Casa'), ('Fijo', 'Fijo'), ('Otro', 'Otro')], default='Celular', max_length=10),
        ),
    ]
