# Generated by Django 2.2.5 on 2019-10-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191003_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Favoritos', 'Favoritos'), ('Amigos', 'Amigos'), ('Conocidos', 'Conocidos'), ('Trabajo', 'Trabajo'), ('Escuela', 'Escuela')], default='Todos', max_length=20),
        ),
    ]
