# Generated by Django 2.2.5 on 2019-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191003_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='label',
            new_name='address_label',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='label',
            new_name='phone_label',
        ),
        migrations.RemoveField(
            model_name='email',
            name='label',
        ),
        migrations.AddField(
            model_name='email',
            name='email_label',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Casa', 'Casa'), ('Trabajo', 'Trabajo'), ('Otro', 'Otro')], default='Principal', max_length=10),
        ),
    ]
